### ISSUE TITLE
Debian 9 dependencies issue

### ISSUE THREAD

**Issue by hoijui** [sk1project/sk1-wx#189]
I have package `libmagickwand-6.q16-6` installed, but `python-sk1-2.0rc3_debian_9_amd64.deb` fails to install becasue it wants `libmagickwand-6.q16-3`:

	sudo dpkg -i python-sk1-2.0rc3_debian_9_amd64.deb
	Selecting previously unselected package python-sk1.
	(Reading database ... 465857 files and directories currently installed.)
	Preparing to unpack .../python-sk1-2.0rc3_debian_9_amd64.deb ...
	Unpacking python-sk1 (2.0rc3) ...
	dpkg: dependency problems prevent configuration of python-sk1:
	 python-sk1 depends on libmagickwand-6.q16-3; however:
	  Package libmagickwand-6.q16-3 is not installed.
	
	dpkg: error processing package python-sk1 (--install):
	 dependency problems - leaving unconfigured
	Processing triggers for mime-support (3.62) ...
	Processing triggers for gnome-menus (3.31.4-3) ...
	Processing triggers for desktop-file-utils (0.23-4) ...
	Processing triggers for hicolor-icon-theme (0.17-2) ...
	Errors were encountered while processing:
	 python-sk1

this `-3` vs `-6` difference... is it a real issue, or just a too thightly defined dependency?

**Comment by sk1project** [comment]
@hoijui try using rc4 package. It seems the issue has been fixed.
https://downloads.sk1project.net/sk1/nightbuilds/Debian/

**Comment by hoijui** [comment]
@sk1project 
I tried rc4, and the same issue persists. it still wnats the smae dependency `libmagickwand-6.q16-3`, while debian 9 has `libmagickwand-6.q16-6`.

**Comment by sk1project** [comment]
@hoijui we investigated this question and found that Debian 9 (Stretch) uses libmagickwand-6.q16-3

https://packages.debian.org/stretch/libmagickwand-6.q16-3

Package libmagickwand-6.q16-6 is from Debian 10 (Busters):

https://packages.debian.org/buster/libmagickwand-6.q16-6

It seems you forced installation for newer ImageMagick but it breaks system consistency. If you need using  libmagickwand-6.q16-6 just compile sK1 frome source code against newer package.
